version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - containedctx
    - copyloopvar
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errorlint
    - exhaustive
    - fatcontext
    - goconst
    - godot
    - govet
    - ineffassign
    - makezero
    - mirror
    - misspell
    - nilerr
    - nilnil
    - nosprintfhostport
    - predeclared
    - reassign
    - revive
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
